### ISSUE TITLE
Can I use the data which is received from callbacks framgrabber.onFrameChanged() and framgrabber.onNewFrame() to feed to  ffmpeg to generate a video 

### ISSUE THREAD

**Issue by peererror** [smasherprog/Screen_Capture#10]
I want to record the screen in a video file So I need to pass the data which is received from   framgrabber.onNewFrame() and framgrabber.onFrameChanged()  callbacks to ffmpeg can you please tell in what formats I will receive data or should convert it to some other format

**Comment by smasherprog** [comment]
Yeah I should document that.
The data is raw, in rgba 4 bytes per pixel for all platforms.

**Comment by smasherprog** [comment]
At least on ubuntu, mac os and windows Xp and up as those are the only platforms that I could test on.

**Comment by smasherprog** [comment]
Also, the onFrameChanged only sends back DIFS. The onNewFrame will be the entire screen every time even if there are no changes.

**Comment by peererror** [comment]
thanks for the response I will test and get back .. 👍

**Comment by peererror** [comment]
I was able to encode images into video stream but I am getting 10 FPS. is there a way get up to 18 to 20 frames/sec currently I am encoding at 1080p I am trying to do it on 25fps .

**Comment by smasherprog** [comment]
Sure, you can go as fast as your system will allow.

setFrameChangedInterval(1)   to go as fast as possible
https://github.com/smasherprog/Screen_Capture/blob/master/Example/Screen_Capture_Example.cpp#L74

Also, if you are trying to go as fast as you can , make sure you are only capturing the monitors you want
 https://github.com/smasherprog/Screen_Capture/blob/master/Example/Screen_Capture_Example.cpp#L71

**Comment by smasherprog** [comment]
And make sure to set only the callbacks you are interested in so that work wont be done if you dont need it. For example, the mouse callbacks.

**Comment by smasherprog** [comment]
Since you are using ffmpeg, have you tried the built in tools?
https://trac.ffmpeg.org/wiki/Capture/Desktop

**Comment by smasherprog** [comment]
Closing this until I hear more
