### ISSUE TITLE
Screen capturing is broken on OS X devices

### ISSUE THREAD

**Issue by SMemsky** [smasherprog/Screen_Capture#15]
Hello!
Current implementation of `CGFrameProcessor::ProcessFrame()` seems to be unreliable and, sometimes, completely broken.
Apple CG's documentation is far from complete, but here are some points i discovered while trying to make screenshot myself:
1) Image width may be actually smaller, than pixels per row in image data. (this was my main problem)
2) Image bitmap data might be stored in different formats across different devices.

## How to deal with that?
Here is how I deal with these problems:
```c++
// First, capture the image
CGImageRef const capturedImage = /* any way of capturing image, be it CGWindowListCreateImage or CGDisplayCreateImage */;

// Second, get bitmap and alpha data info
CGBitmapInfo const bitmapInfo = CGImageGetBitmapInfo(capturedImage);
CGImageAlphaInfo const alphaInfo = CGImageGetAlphaInfo(capturedImage);
```
In order to do screenshots on any platform, one must be ready to handle any combination of bitmap and alpha structures.
Now I will only look at 32-bit Little-Endian bitmap format with Alpha being the first byte.
Note that alpha is unused in screenshot capturing, so we should not care about its representation.
```c++
// Ensure 32-bit LE
assert(bitmapInfo & kCGBitmapByteOrder32Little);
// Ensure alpha is at the first byte and has any format (we'll just skip it while reading)
assert(
    alphaInfo == kCGImageAlphaFirst ||
    alphaInfo == kCGImageAlphaNoneSkipFirst ||
    alphaInfo == kCGImageAlphaPremultipliedFirst);
```
Many implementations add padding at the end of each pixel row. In my case (1366x768 screen), it was 10 completely transparent pixels.
```c++
// Get real image width and height, this has NOTHING to do with size of image data provided
std::size_t const width = CGImageGetWidth(capturedImage);
std::size_t const height = CGImageGetHeight(capturedImage);

// This is the actual row size. Many implementations add some padding at the end of each row
std::size_t const bytesPerRow = CGImageGetBytesPerRow(capturedImage);

std::size_t const bytesPerPixel = CGImageGetBitsPerPixel(capturedImage) / 8u;
std::size_t const pixelsPerRow = bytesPerRow / bytesPerPixel;
```
Now let's get the data provider and copy all the data from it:
```c++
GDataProviderRef const dataProvider = CGImageGetDataProvider(capturedImage);
if (!dataProvider) {
    // Handle this. I think that this can only happen if the passed CGImageRef was NULL
}

// As this will copy the data, it needs to be freed separately from the captured image.
CFDataRef const rawPixelData = CGDataProviderCopyData(dataProvider);
```
Then the data can be accessed as you like. Make sure to take into account bitmap and alpha info and perform all needed conversions for library's internal format
```c++
// Cast the byte pointer to whatever you like
uint32_t const * const dataPointer = reinterpret_cast<uint32_t const *>(CFDataGetBytePtr(rawPixelData));

// And access it like this:
for (unsigned row = 0; row < height; ++row) {
    for (unsigned column = 0; column < width; ++column) {
        // Note that pixelsPerRow includes padding pixels
        /* whatever */ = dataPointer[row * pixelsPerRow + column];
    }
}
```

Also note that src/ios/CGFrameProcessor.cpp is a mix of 4-space and tab-character indentation. This is an important issue, as tabulation character may be displayed as four, two or even eight spaces.

**Comment by smasherprog** [comment]
Nice, Ill implement these changes, or if you already have it done, can you issue a PR?

**Comment by SMemsky** [comment]
No, I don't think I sufficiently familiar with the codebase to make any changes in this project :D
By the way, I strongly recommend you to add license information and contribution guidelines to your project 😉

**Comment by smasherprog** [comment]
alright, thanks for the info. You're right, ill get the code updated and add the license. It was an oversight on my part

**Comment by smasherprog** [comment]
I was out this weekened away from my mac test device. Ill implement your suggestions tomorrow and release an update.

Thanks for the great feedback. Ill also be adding a license for MIT -- good catch

**Comment by smasherprog** [comment]
Updated the mac build. Please give it a try. 
I couldnt get my mac to  have extra bytes on each row, so im not sure if it works, but it should

**Comment by SMemsky** [comment]
It works, but colors are messed up. You also need to take care of bitmap pixel byte order. In my case RGB has turned into BGR.
Original (rgb(31, 63, 127))
![Original color](https://pp.userapi.com/c637426/v637426241/76f2d/XuVnqy7-_6s.jpg)
Screenshot (background turns into rgb(127, 63, 31))
![Resulting image](https://pp.userapi.com/c637426/v637426241/76f34/7H-YhpD_n8M.jpg)

**Comment by smasherprog** [comment]
Alright cool.. getting closer. Ill add those later today.

**Comment by smasherprog** [comment]
I have investigated this and here is what I found. . . 

What you are experiencing is correct.  You can read on it here https://www.gamedev.net/topic/494153-rgb-is-actually-bgr/

As a note, the below explanation talks about Directx (D3D)  but is the same for other platforms as well.

The post by Namethatnobodyelsetook  is the one which describes this

> Actually, all D3D formats are named such that when read as the appropriate word size, the bits are where you'd expect. I think it's not actually mentioned in the docs, but is in D3D9types.h (just press F12 when your cursor is on a format name and VStudio should whisk you away to the appropriate header).
> 
> If you read A8R8G8B8 as a DWORD, and A will be in bits 24-31, R in 16-23, G in 8-15, and B in 0-7. A1R5G5B5 will have A in bit 15 if you read it as a WORD. If you're reading A8R8G8B8 as bytes you'll get blue first because of the endian of X86 processors. 


So, all formats so far on the platforms I have tested on: mac, linux and windows all follow the same byte format of rgba, but its little-endian on int boundaries so it seems backwards,

I think I might add a conversion function or leave it up to the user since the combination of desired formats is pretty large...

What are your thoughts?

**Comment by SMemsky** [comment]
First, you'll need to decide on which bitmap structure this lib provides. Readme says:

> raw rgba 32 bits per pixel

What does this may mean?
* [R, G, B, A, R, B, ...] - sequentially byte-by-byte  (as uint8) (BE RGBA)?
* [RGBA, RGBA, ...] - sequentially pixel-by-pixel (as uint32) in host endianness?
* Any other?

In any case, I think that when needed you will have to do conversion to library's uniform bitmap format.

**Comment by SMemsky** [comment]
Hmm, it seems to be a surprisingly hard task to find sufficient amount of documentation about CG API. Looks like I've found a [SO answer](http://stackoverflow.com/a/7300698) which describes a way of getting image data in the format you'll need. I have not tested it though.

**Comment by smasherprog** [comment]
You're right that I need to settle on a specific format. My preference is to use the current format rgba -- pixel by pixel-- solely because it seems to be the native formats on the major platforms. I dont want the library to convert pixel formats because it would be extra work that may or may not actually be needed. 

I think that i'll add a user-defined callback function called

onImage

that will run before 

onFrameChanged
onNewFrame
onMouseChanged

so a user can change the image format if they want. Ill pass in the image buffer, size, etc and let the user munge the image. Ill update the example as well to show how to convert to the R, G, B, A

Thoughts?

**Comment by smasherprog** [comment]
Great feedback btw.

**Comment by smasherprog** [comment]
Updated the Library, example and decided on a pixel format as well.
onImage added as a callback to change the image
Also, the common pixel format on Mac,Windows and Linux is BGRA, so i have decided to use that format.

Let me know if this works for you...

**Comment by SMemsky** [comment]
Provided example works well on my machine. Yay.
So the format is BGRA with Blue byte being first (Big Endian)? Please make sure to state so in README :)
Also the new `onImage` callback looks interesting. But as its main goal is conversion, then what about renaming it to something more obvious? Also providing some default conversion functions would be nice.
Note that if you choose to stay on a specific format, then you will have to provide fallback conversion when needed.

**Comment by SMemsky** [comment]
Sorry, misclicked :man_shrugging:

**Comment by smasherprog** [comment]
So, yeah I was wrong about the pixel format. I checked on my test devices/OS and it seemed to be consistent on Mac, linux and windows.
The onImage callback isnt named the best.... Ill try to update this in the future.
I have a couple of ideas to make this better as well.

**Comment by smasherprog** [comment]
I am going to change the onNewFrame callback to make it so users have direct access to the image like the onImage function. Then, any changes can be made there, this will be better I think.

Ill make the change later today

**Comment by smasherprog** [comment]
Updated the API and did a new release. I believe that I settled on how to tackle the issues that you have addressed. I removed the onImage function and let the user convert the image if they want. I added an ExtractAndConvertToRGBA function to the public API. since the RGBA format is the most commonly used, this will be the only conversion function that I add to this library.

**Comment by smasherprog** [comment]
Also, the examples have been updated to reflect these changes

**Comment by smasherprog** [comment]
Closing this issue. Let me know if there are any additional changes needed.
