### ISSUE TITLE
c++14 only?

### ISSUE THREAD

**Issue by blitz-research** [smasherprog/Screen_Capture#16]
Hi,

This look good, but it appears to be c++14 only, is this correct?

Any chance it could be 'fixed' to work with c++11?

Bye!
Mark

**Comment by smasherprog** [comment]
I'll have to take a look. I really dont want to go backwards, but ill take a look. If its minimal, then yeah I'll drop the c++ 14 features.
Ill be taking a look at this today or tomorrow. If you have any suggestions, issue a PR, they are always welcome

**Comment by smasherprog** [comment]
I hit the wrong button when closing this...

**Comment by blitz-research** [comment]
Actually, I think I should be able to upgrade my project to c++14 so this
might not be necessary.

**Comment by smasherprog** [comment]
Ok, great.. I am always trying to move with the latest c++ standard.

**Comment by smasherprog** [comment]
Closing this. I would like the code to be current with the standard and supported by the big three compilers, which c++14 is
