### ISSUE TITLE
Using in QtCreator

### ISSUE THREAD

**Issue by KevinBLT** [smasherprog/Screen_Capture#19]
Hello,

I am having troubles using this in QtCreator.
I have tried compiling it in VS2015, it works.

But I also get Linking Errors in QtCreator.
Can't I just include the headers and compile it into my application?

I have no idea at the moment where to start.

**Comment by smasherprog** [comment]
Ill post in about 7-8 hours

**Comment by smasherprog** [comment]
In general you can include headers and source files to build this project.
If you are using just regular VS, then you can generate a project using cmake,then add that as a reference to your current project.

You can review the https://github.com/smasherprog/Screen_Capture/blob/master/src/CMakeLists.txt  file for the platform specific files included.

Generally, you would just add the file above to your own cmake build process. But, it sounds like you arent using cmake.

Do you use vcpkg  at all? I am considering adding this project there . .

**Comment by SMemsky** [comment]
You can't just include headers and compile. It's not a single-header library. As an easy workaround, you can compile this lib separately and then use it in QtCreator just like any other lib. [How to add libs](http://stackoverflow.com/q/718447)

**Comment by smasherprog** [comment]
Thanks for the input SMemsky.

I am closing this issue. If you need more help post a comment and I'll try and help.

**Comment by JulianMined** [comment]
Hello, i compiled the lib and included it - now i got the follow error: 

> liblibScreen_Capture.a(GetMonitors.cpp.o): undefined reference to symbol 'XOpenDisplay'
