### ISSUE TITLE
The frame rate

### ISSUE THREAD

**Issue by yangwuan55** [smasherprog/Screen_Capture#20]
I use the demo has a low frame rate.Almost 2fps at macos,why?
And how can I include the library to JNI?

**Comment by smasherprog** [comment]
If you are using the example, make sure you are not saving images to disk. The saving of files to disk is a slow operation. I save images to disk to ensure the program is working properly.

**Comment by smasherprog** [comment]
Please let me know if that was the issue

**Comment by yangwuan55** [comment]
@smasherprog If I don't save images to disk less than 20fps.I use mac pro.
![image](https://user-images.githubusercontent.com/5218120/26959859-4ba5a66e-4d05-11e7-91bb-16396d231f7d.png)

![image](https://user-images.githubusercontent.com/5218120/26959928-e497d1f8-4d05-11e7-903e-66d973eb5576.png)

**Comment by yangwuan55** [comment]
If I use the objective-c to capture the fps can more than 40fps.

**Comment by smasherprog** [comment]
There is a limit that is set   setFrameChangeInterval 
set it to 1 and see if that makes it faster

**Comment by smasherprog** [comment]
the code uses objective c to capture the frames 
https://github.com/smasherprog/Screen_Capture/blob/master/src/ios/CGFrameProcessor.cpp

**Comment by smasherprog** [comment]
also if you want to capture the entire monitor, not the differences, then dont set the callback for onFrameChanged

This will improve performance as well

**Comment by yangwuan55** [comment]
Thanks.

**Comment by smasherprog** [comment]
Did this improve the screen capture rate?
I do have some extra work going on inside the capture which I can turn more. It would give a slight bump in performance..

I want to know if this is fast enough, if not, let me know and ill try to make this better.
