### ISSUE TITLE
Linker Error in Screen capture Example program

### ISSUE THREAD

**Issue by pacificdragon** [smasherprog/Screen_Capture#9]
![untitled](https://cloud.githubusercontent.com/assets/12509045/23853061/e03e57a6-0810-11e7-8482-928bdb265e08.png)
Unable to compile it please help
Screen_Capture_Example.obj : error LNK2019: unresolved external symbol "public: __cdecl SL::Screen_Capture::ScreenCaptureManager::ScreenCaptureManager(void)" (??0ScreenCaptureManager@Screen_Capture@SL@@QEAA@XZ) referenced in function main

**Comment by smasherprog** [comment]
Ill take a look at this shortly. It looks like The libScreen_Capture isnt being linked.  Try Adding a reference manually and see if that fixes this. 
This isnt something you should have to do though, its probably a misconfiguration that ill fix

**Comment by smasherprog** [comment]
I just downloaded and did a clean build from my non dev computer which i dont normally use to build things. Everything worked as expected.

I used cmake 3.7.2 and visual studio 2015. 
My regular build is based on 2017 and it works there as well. 

Could you try deleting everything and trying again?

**Comment by pacificdragon** [comment]
I m using cmake 3.8.0 and visual studio 2013.
Hope it will work after upgrading. Also  linked library manually still same problem.
Anyway Thanks

**Comment by smasherprog** [comment]
It could be that VS 2013 doesnt support the features that I use. VS 2017 community == Visual studio Profession and is free. 
Try 2017 and see how that goes...

**Comment by smasherprog** [comment]
Please let me know how it goes using 2017.
Im going to close this. If you try 2017 and still have the issue, add a comment to this and ill reopen it and take a second look.
